// <auto-generated />
using Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Databases.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118195936_View-Livros")]
    partial class ViewLivros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAs");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Codigo");

                    b.ToTable("Assunto", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descricao = "Engenharia de Software"
                        },
                        new
                        {
                            Codigo = 2,
                            Descricao = "Arquitetura de Sistemas"
                        },
                        new
                        {
                            Codigo = 3,
                            Descricao = "Design Patterns"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Codigo");

                    b.ToTable("Autor", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Nome = "Robert C. Martin"
                        },
                        new
                        {
                            Codigo = 2,
                            Nome = "Martin Fowler"
                        },
                        new
                        {
                            Codigo = 3,
                            Nome = "Eric Evans"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Livro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cod");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Codigo");

                    b.ToTable("Livro", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            AnoPublicacao = "2017",
                            Edicao = 1,
                            Editora = "Prentice Hall",
                            Titulo = "Clean Architecture"
                        });
                });

            modelBuilder.Entity("Livro_Assunto", b =>
                {
                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("int");

                    b.Property<int>("Livro_Cod")
                        .HasColumnType("int");

                    b.HasKey("Assunto_CodAs", "Livro_Cod");

                    b.HasIndex("Livro_Cod");

                    b.ToTable("Livro_Assunto");

                    b.HasData(
                        new
                        {
                            Assunto_CodAs = 1,
                            Livro_Cod = 1
                        });
                });

            modelBuilder.Entity("Livro_Autor", b =>
                {
                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("int");

                    b.Property<int>("Livro_Cod")
                        .HasColumnType("int");

                    b.HasKey("Autor_CodAu", "Livro_Cod");

                    b.HasIndex("Livro_Cod");

                    b.ToTable("Livro_Autor");

                    b.HasData(
                        new
                        {
                            Autor_CodAu = 1,
                            Livro_Cod = 1
                        },
                        new
                        {
                            Autor_CodAu = 2,
                            Livro_Cod = 1
                        });
                });

            modelBuilder.Entity("Livro_Assunto", b =>
                {
                    b.HasOne("Domain.Entities.Assunto", null)
                        .WithMany()
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Livro_Assunto_FKIndex1");

                    b.HasOne("Domain.Entities.Livro", null)
                        .WithMany()
                        .HasForeignKey("Livro_Cod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Livro_Assunto_FKIndex2");
                });

            modelBuilder.Entity("Livro_Autor", b =>
                {
                    b.HasOne("Domain.Entities.Autor", null)
                        .WithMany()
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Livro_Autor_FKIndex1");

                    b.HasOne("Domain.Entities.Livro", null)
                        .WithMany()
                        .HasForeignKey("Livro_Cod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Livro_Autor_FKIndex2");
                });
#pragma warning restore 612, 618
        }
    }
}
